ny_taxi_modelling:
    target: dev
    outputs:
        dev:
            type: snowflake
            database: "NYC_TLC"
            user: "{{ mage_secret_var('<SNOWFLAKE_USER>') }}"
            password: "{{ mage_secret_var('<SNOWFLAKE_PASSWORD>') }}"
            role: "ACCOUNTADMIN"
            schema: "GOLD"
            account: "{{ mage_secret_var('<SNOWFLAKE_ACCOUNT>') }}"
            warehouse: "{{ mage_secret_var('<SNOWFLAKE_WH>') }}"
